export const SET_PETS = 'SET_PETS'
export const ERROR = 'ERROR'
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER'
export const SET_GLOSSARY = 'SET_GLOSSARY'
export const SET_PEOPLE = 'SET_PEOPLE'
export const GET_PERSON = 'GET_PERSON'

// export const SET_RESOURCES = 'SET_RESOURCES'
// export const SET_CATEGORIES = 'SET_CATEGORIES'
//
export const GET_PET = 'GET_PET'
export const CHG_CURRENT_PET = 'CHG_CURRENT_PET'
export const CLEAR_CURRENT_PET = 'CLEAR_CURRENT_PET'
export const CONFIRM_DELETE_PET = 'CONFIRM_DELETE_PET'
//
// export const CURRENT_CAT = 'CURRENT_CAT'
// export const ADD_CATEGORY = 'ADD_CATEGORY'
// export const RESET_ADD_CAT_FORM = 'RESET_ADD_CAT_FORM'
// export const CHANGE_CURRENT_CATEGORY = 'CHANGE_CURRENT_CATEGORY'
//
// export const CHANGE_SEARCH_CRITERIA = 'CHANGE_SEARCH_CRITERIA'
